### ISSUE TITLE
Can you add id field in operation type to support presisted queries?

### ISSUE THREAD

**Issue by hariroshan** [zth/reason-relay#128]
If we use this option in relay.config.js `persistOutput: "./presist.json" ` our queries are persisted in a json file.
In the Relay environment, we will receive this ID in the operation object and text will be null. So can you add id type to operation record.

**Comment by zth** [comment]
Yes, this would be a good addition for sure. Mind sending a PR? 

You can work around the binding missing easily until that is released - do you know how already or do you want me to tell you?

**Comment by hariroshan** [comment]
I know I can add a record field `id` under `ReasonRelay.Network.operation` like so
```
type operation = {
    id: option(string),
    text: string,
    name: string,
    operationKind: string,
  };
```
And everything else should work fine. But the problem is than when presistedQueries are used, `operation.text` field will be `null` and `id` field will be `Some(id)`. To overcome this, I should make `operation.text` field also `option(string)`. And this creates unnecessary states that we need to handle like `id: None, text: None` for example.
A better solution will be to make `operation` type a `SUM` like
```
type presistedQueryOperation = {
  id: string,
  name: string,
  operationKind: string,
};
type simpleQueryOperation = {
    text: string,
    name: string,
    operationKind: string,
  };
type operation = 
    | SimpleQueryOperation(simpleQueryOperation)
    | PresistedQueryOperation(presistedQueryOperation);

``` 
What is your opinion?

**Comment by zth** [comment]
Yeah, I agree with all of those points. However, I'm thinking whether it's worth chasing "fictive" type safety here. I'm inclined to just add `id: string`, not optional, and let the user keep track of which one they're using themselves, depending on whether they have persisted queries or not. 

My reasoning is that while a sum type is more correct, it still won't help point the user in the right direction, since we have no way in the types to know whether we have persisted queries activated or not. To me, that means that _regardles_ of type safety inside of the operation binding, you'll still need to manually keep track of what prop to use based on whether you have persisted queries activated or not. And at that point I think any extra steps just become unecessary/friction.

What do you think about that reasoning?

**Comment by hariroshan** [comment]
Yeah It makes sense. Adding `id: string` is the simplest option. But It should be mentioned in the docs for better usage of the library

**Comment by zth** [comment]
Sure! Would you mind PRing adding the prop? You could also add a comment above the prop definition that people will then see in their editor, like:
```
type operation = {
  /** This will be available when not using persisted queries. */
  text: string,

  /** This will be available only when using persisted queries, and is the ID of the persisted query. */
  id: string,
....
}
```

**Comment by hariroshan** [comment]
I made the edits and sent a pull request. Thanks
