### ISSUE TITLE
Integrate with GraphQL ppx

### ISSUE THREAD

**Issue by jfrolich** [zth/reason-relay#26]
With 1.0 on the way and several improvements in the GraphQL ppx, I think it will be feasible to support Relay. This slightly changes the implementation. With GraphQL ppx we can generate javascript that will look the same as if you'd write Relay by hand in Javascript including tagged template literals etc.

Basically where GraphQL ppx can come in is generating types from the schema (this is generic and is the same for each client), and parsing the JSON output and converting it to Reason datatypes (also generic).

To have the best support we need a "Relay mode" in GraphQL ppx. That will facilitate a few things like how to handle fragments in Relay (as they are global) etc.

I think it would be really great to have a single piece of infrastructure in Reason that can be reused across the GraphQL ecosystem. One of the cool benefits that this would open up, is that now GraphQL fragments and queries can be literally reused across clients. (For instance, if you want to share components between a Gatsby site and a Relay app).

**Comment by zth** [comment]
I'm intrigued by the idea and I hope we can at least integrate this in some capacity. Here's a list of edge cases I can think of that `graphql_ppx` would need to support in order to fully support what ReasonRelay supports now:

## Relay adds custom directives, and some of those directives affect how types should be generated
I think this is mainly about: `@inline`, `@relay(mask: false)` and `@relay(plural: true)`. Let me go through how each affects the output. Here's a run down of how each directive affects the types:

`@inline` can be declared on a fragment definition, and means that this fragment's selections should be _inlined_ wherever it's spread. So if I have `fragment UserInfo_user on User @inline {` and use that `...UserInfo_user`, all the fields `UserInfo_user` declares should always be inlined, regardless of where that fragment is spread.

`@relay(mask: false)` does the same as `@inline`, but "on demand", on a fragment spread directly. So `fragment Avatar_user on User {` used as `...Avatar_user @relay(mask: false)` would inline the fields `Avatar_user` selects, but _only where that spread occurs_.

`@relay(plural: true)` can be defined on a fragment definition, and indicates that this fragment should be recieved as an array and not a single object. `fragment BlogPostsList_blogPosts on BlogPost @relay(plural: true) {`. The only effect this has on the types is that `type fragment = ...` needs to be `type fragment = array(t_fragment)`. 

I _think_ those are all the directives that affect the types as of now. The important thing to know here is that there are no guarantees that the types generated by Relay will match exactly how types are generated via `graphql_ppx`, since the Relay compiler transforms, optimizes and does all sorts of things on your GraphQL operations before they're turned into types. In the vast majority of cases it should be more or less 1:1 with `graphql_ppx`, but it's not _guaranteed_.

## Relay allows you to extend your schema locally by putting `.graphql` files in arbitrary locations
This is useful for more thorough local state management, but also convenient for adding simple extensions to existing types (like`isEditing: Boolean!` on a `BlogPost`). This could probably be circumvented somehow, but this is a feature I want to keep support for.

## Custom scalars are defined in `relay.config.js` and are applied to all type definitions
I think you've talked about having a central configuration for custom scalars in `graphql_ppx` too. In Relay, custom scalars are defined in `relay.config.js` (or via the CLI when running the compiler, but that naturally won't work with `graphql_ppx` involved). They follow a simple key/value convention (`"Cursor": "string"`) and are then inlined into the types.

## Decoding of data must happen after data is retrieved from the store (in the view basically), it cannot happen only when the data is received from the server
This is because of how the Relay cache works. I know you're decoding data one time when it's received from the server in `graphql_ppx`, but that won't work with Relay:
* `null` and `undefined` have distinct meaning in Relay. If `null` is decoded into `undefined` before going into the cache, Relay will think that that data was not actually fetched (that's what `undefined` in the cache means, `null` in the cache is fetched but `null`), and things will break. This is the biggest problem, because it means that data supplied to Relay from the cache will always have to be `null`, or it'll be treated as missing. This happens here for instance: https://github.com/facebook/relay/blob/df17e69c2f07423f31d74d5c40e0b35273435688/packages/relay-runtime/store/RelayReader.js#L107-L111 where Relay checks explicitly for `undefined` and treats it differently than `null`.
* Decoding unions to objects and saving that to the cache as-is _might_ produce issues, but I'm not fully sure about that. This could probably be looked up and tested.

## Having the compiler operate on JS files produced by BS rather than Reason files means it'll report diagnostics and so on in the wrong place
In the current approach, the compiler scans all _Reason files_ and extracts GraphQL operations from them. For all Relay knows, it's operating on `.re` files. This means that all errors and diagnostics will be reported for the right locations in the right files. If the compiler is instead scanning the generated `.bs.js` files, error reporting and diagnostics will be reported for the wrong place.

Now, this is probably not more than a cosmetic issue at this point (it'll say `SomeFile.bs.js` instead of `SomeFile.re` which is where the code we're working on is actually located). *But*, I think the Relay team will work on integrating their compiler deeper into editors (like VSCode), adding language server capabilities to the compiler basically. Or so I've heard at least. And that type of integration simply wouldn't be possible to use in a setup where the files you have you source in (`.re`) isn't the same as the compiler operates on.

## Passing the correct fragment object around must be ensured at the type level
In Flow and TypeScript, Relay ensures that you pass the right objects with the right fragment spread to your fragment hooks via structural typing. Basically, and object with a fragment spread will have a prop `"$fragmentRefs": SomeFragment.ref`, and Relay uses that to match structurally and ensure that the object you're passing has the right fragment spread on it.

Since records aren't structurally typed, I currently solve this by adding a `getFragmentRefs()` method (both on the JS and Reason side) to each object where a fragment has been spread. That method just returns itself, but it allows me to return a  `Js.t` with all fragment refs for that object in Reason. I can then structurally match on that `Js.t` to ensure that the right fragment `use` hook gets the right value.

This would also need to be solved in some way via `graphql_ppx`. I'm sure there's some better way of doing this than what I've done here, but it'll need to be handled.

I'll add more to this list a bit later, but this is a start.

**Comment by jfrolich** [comment]
> ## Relay adds custom directives, and some of those directives affect how types should be generated
> I think this is mainly about: `@inline`, `@relay(mask: false)` and `@relay(plural: true)`. Let me go through how each affects the output. Here's a run down of how each directive affects the types:
> 
> `@inline` can be declared on a fragment definition, and means that this fragment's selections should be _inlined_ wherever it's spread. So if I have `fragment UserInfo_user on User @inline {` and use that `...UserInfo_user`, all the fields `UserInfo_user` declares should always be inlined, regardless of where that fragment is spread.

This would generally need to map the default behavior for other clients (as inlining is the only way to do fragments)

> `@relay(mask: false)` does the same as `@inline`, but "on demand", on a fragment spread directly. So `fragment Avatar_user on User {` used as `...Avatar_user @relay(mask: false)` would inline the fields `Avatar_user` selects, but _only where that spread occurs_.
> 
> `@relay(plural: true)` can be defined on a fragment definition, and indicates that this fragment should be recieved as an array and not a single object. `fragment BlogPostsList_blogPosts on BlogPost @relay(plural: true) {`. The only effect this has on the types is that `type fragment = ...` needs to be `type fragment = array(t_fragment)`.

Hmm interesting. Is it just to enforce that a fragment can only be used in an array context? Why is that?

> I _think_ those are all the directives that affect the types as of now. The important thing to know here is that there are no guarantees that the types generated by Relay will match exactly how types are generated via `graphql_ppx`, since the Relay compiler transforms, optimizes and does all sorts of things on your GraphQL operations before they're turned into types. In the vast majority of cases it should be more or less 1:1 with `graphql_ppx`, but it's not _guaranteed_.

As far as what the users sees, that should be consistent with the query. If there are certain behaviors we should indeed implement them (but they should be documented because the user should be aware if something different comes back than what they expect).

> ## Relay allows you to extend your schema locally by putting `.graphql` files in arbitrary locations
> This is useful for more thorough local state management, but also convenient for adding simple extensions to existing types (like`isEditing: Boolean!` on a `BlogPost`). This could probably be circumvented somehow, but this is a feature I want to keep support for.

Cool feature. This indeed might be a bit more tricky to implement in the PPX. We basically need to scan the project for `.graphql` files and extend the schema.

> ## Custom scalars are defined in `relay.config.js` and are applied to all type definitions
> I think you've talked about having a central configuration for custom scalars in `graphql_ppx` too. In Relay, custom scalars are defined in `relay.config.js` (or via the CLI when running the compiler, but that naturally won't work with `graphql_ppx` involved). They follow a simple key/value convention (`"Cursor": "string"`) and are then inlined into the types.

Are these custom scalars a `Relay` convention or a `reason-relay` convention? In the latter we can perhaps standardize on a `bsconfig.json` config for this (alike to configuring `gentype`). In the former we should probably keep it in `relay.config.js`.

> ## Decoding of data must happen after data is retrieved from the store (in the view basically), it cannot happen only when the data is received from the server
> This is because of how the Relay cache works. I know you're decoding data one time when it's received from the server in `graphql_ppx`, but that won't work with Relay:

Most clients work like this, so that is not a problem.

> * `null` and `undefined` have distinct meaning in Relay. If `null` is decoded into `undefined` before going into the cache, Relay will think that that data was not actually fetched (that's what `undefined` in the cache means, `null` in the cache is fetched but `null`), and things will break. This is the biggest problem, because it means that data supplied to Relay from the cache will always have to be `null`, or it'll be treated as missing. This happens here for instance: https://github.com/facebook/relay/blob/df17e69c2f07423f31d74d5c40e0b35273435688/packages/relay-runtime/store/RelayReader.js#L107-L111 where Relay checks explicitly for `undefined` and treats it differently than `null`.
> * Decoding unions to objects and saving that to the cache as-is _might_ produce issues, but I'm not fully sure about that. This could probably be looked up and tested.

This will definitely be a problem. We cannot pass ReasonML types back to the client. I saw you accounted for this in `reason-relay` in a decoding function. (Actually this is a problem for each client when you communicate with the cache). I am working with GraphQL ppx to support `serialization`.

When you get data from the cache (or raw JSON from the server for that matter), it will be typed as `Fragment.Raw.t` this means that it is typed exactly so that it maps 1:1 with the raw data representation (it still has records etc. as they map nicely with javascript, but it will have a `Js.Nullable.t` for optionals). Then you can call `Query.parse` to convert the raw data to a nice Reason representation. If you need to interface with the cache (for instance for optimistic updates or cache updates), you can serialize the reason data back to the canonical representation with `Query.serialize`. All of this can happen in the library of course (these functions are part of the `definition` that you pass to library functions).

> ## Having the compiler operate on JS files produced by BS rather than Reason files means it'll report diagnostics and so on in the wrong place
> In the current approach, the compiler scans all _Reason files_ and extracts GraphQL operations from them. For all Relay knows, it's operating on `.re` files. This means that all errors and diagnostics will be reported for the right locations in the right files. If the compiler is instead scanning the generated `.bs.js` files, error reporting and diagnostics will be reported for the wrong place.
> 
> Now, this is probably not more than a cosmetic issue at this point (it'll say `SomeFile.bs.js` instead of `SomeFile.re` which is where the code we're working on is actually located). _But_, I think the Relay team will work on integrating their compiler deeper into editors (like VSCode), adding language server capabilities to the compiler basically. Or so I've heard at least. And that type of integration simply wouldn't be possible to use in a setup where the files you have you source in (`.re`) isn't the same as the compiler operates on.

Good point. I think we need to keep the language plugin to have tight integration. It can be much simpler as the responsibility of the language plug-in will be smaller.

The cool thing with the new approach is that the language plugin will be optional. So you could opt to just run vanilla relay (with a slightly worse experience).

> ## Passing the correct fragment object around must be ensured at the type level
> In Flow and TypeScript, Relay ensures that you pass the right objects with the right fragment spread to your fragment hooks via structural typing. Basically, and object with a fragment spread will have a prop `"$fragmentRefs": SomeFragment.ref`, and Relay uses that to match structurally and ensure that the object you're passing has the right fragment spread on it.
>
> Since records aren't structurally typed, I currently solve this by adding a `getFragmentRefs()` method (both on the JS and Reason side) to each object where a fragment has been spread. That method just returns itself, but it allows me to return a `Js.t` with all fragment refs for that object in Reason. I can then structurally match on that `Js.t` to ensure that the right fragment `use` hook gets the right value.
> 
> This would also need to be solved in some way via `graphql_ppx`. I'm sure there's some better way of doing this than what I've done here, but it'll need to be handled.
> 
> I'll add more to this list a bit later, but this is a start.

Yes, this is currently solved in GraphQL ppx by typing to Fragment.t (as they are inline), to be able to do that the fragment module needs to be in scope. If there are more than one fragments artificial fields references are created that point to the same data but have different types so you don't need polymorphism/structural typing. If the Fragment module is not in scope (we can also choose to require the fragment module to be in scope), we can choose type them as polymorphic variants (as we cannot reference the fragment type), so the component that receives the fragment can check if it's the right type.

**Comment by zth** [comment]
I'm going through old issues cleaning up some, and I'm going to close this for now. Summarizing why: the benefit of using `graphql_ppx` in this case isn't clear to me, other than sharing infrastructure. I'd be all for that if the infrastructure was compatible, but in my mind it's not - Relay, what the Relay compiler outputs and how it works is simply different in enough ways that I don't see the benefits outweighing the cons.

I'm probably going to revamp the type generation of ReasonRelay as Relay releases its new compiler later this year, at which point looking into using parts of `graphql_ppx` might be interesting. I'll revisit this then hopefully!

**Comment by jfrolich** [comment]
It's a different approach. Or you generate minimal reason code with the relay compiler, or you generate all reason code with the relay compiler. You can leverage language support of graphql primitives with `graphql-ppx` instead of generating a bunch of reason code. I see why you did the latter as `graphql_ppx` was quite immature at that point! But the former is more powerful, faster, elegant and way more typesafe. And it's probably trivial to implement with the new version of `graphql-ppx`. The need is not too strong to switch graphql clients at the moment but when my company makes a move I will put some work into a PR to make this compatible with `graphql-ppx`, and then we can see it's worth a merge or a fork :).

**Comment by jfrolich** [comment]
> I'd be all for that if the infrastructure was compatible, but in my mind it's not - Relay, what the Relay compiler outputs and how it works is simply different in enough ways that I don't see the benefits outweighing the cons.

GraphQL is a standard. `graphql-ppx` creates language primitives for operations and fragments. Relay is just a client with some fancy tooling (you have to hook into that compiler for sure). But saying they are incompatible is not true. I can definitely help you guide leveraging `graphql-ppx`, that way the surface area of this lib becomes smaller and you get a lot of stuff for free. But if the appetite is not there that's fine.

**Comment by jfrolich** [comment]
> I'm probably going to revamp the type generation of ReasonRelay as Relay releases its new compiler later this year, at which point looking into using parts of graphql_ppx might be interesting. I'll revisit this then hopefully!

Yeah that's exactly the use case. You don't need "parts of graphql-ppx" for that.
