### ISSUE TITLE
Why is `getFragmentRefs()` a function

### ISSUE THREAD

**Issue by Arnarkari93** [zth/reason-relay#34]
I am working on integrating `reason-relay` with `NextJs` and I am having problems with the hydration. `NextJs` server injects data fetched into a script tag (__NEXT_DATA__) on the page which is then used on the client-side. 
The problem with this is that we can't hydrate the function `getFragmentRefs` since this is just text data. But is there a reason why `getFragmentRefs` is a function and not just a string identifier?

I would be glad to submit a PR for changing this from a function to string if that is possible. It would be good to get some pointers for where to get started.

Here is an example project: https://github.com/zeit/next.js/pull/12080

**Comment by zth** [comment]
Hi!

`getFragmentRefs` is an actual function because we need to convert a record (that's nominally typed) to a `Js.t` (which is structurally typed), and because of how Relay works that needs to be the exact same object.  `getFragmentRefs` just returns the object where it has been defined, which allows us to change the types. 

For some background I used to have another solution where I emitted `external`'s for each record with fragments on, that would do the same thing but one function for each individual record with fragments. But I moved away from this as using that was a pain basically (lots of names to keep track of, and lots of things you needed to know to make things work).

Now, hydrating with Relay (and next) should actually be done roughly like this:
- When you've fetched all data you want with Relay on the server, you can serialize the store into a format you can use for hydrating like this:

```reason
let records = ReasonRelay.(
  environment // Your environment
    ->Environment.getStore
    ->Store.getSource
    ->RecordSource.toJSON
);
```

This can then be used to hydrate your store when creating it:
```reason
let environment =
  ReasonRelay.Environment.make(
    ~network,
    ~store=
      ReasonRelay.Store.make(
        ~source=ReasonRelay.RecordSource.make(~records=records),
        ~gcReleaseBufferSize=50,
        (),
      ),
    (),
  );
```
Notice `ReasonRelay.RecordSource.make`.

Here's a project with Next and ReasonRelay working together: https://github.com/sync/pollen-tracker

Thanks for raising this, I should really document the SSR parts. Let me add another issue about that. And please try what I wrote and get back to me with whether it worked.

**Comment by Arnarkari93** [comment]
Thank you! 🙏  
I figured out that I was not calling the `useQuery` hook in the component. Instead, I was trying to pass down the data I got from `getInitialProps`. I will update my PR to the `NextJs` examples. We could link to that example when merged when creating an SSR documentation.
