### ISSUE TITLE
Suspense with fragments

### ISSUE THREAD

**Issue by Arnarkari93** [zth/reason-relay#51]
Fragments will suspend when their required data is not ready. In javascript, you would pass in a nullable fragment reference. How would you do this in reason? Since fragment references are not optional.

Would it make sense to move the `getFragmentRefs()` function "one level" up? So it is more inline how it is done in plain javascript?
```reason
/// now
type response_field = {
  getFragmentRefs: unit => { ... }
};
type response = { field: option(response_field)};

// perposal
type response_field = {...not_sure_about_this };
type response = {
 field: option(response_field),
 getFragmentRefs: unit => { ... }
};
```

**Comment by zth** [comment]
Hi @Arnarkari93 , thanks for reporting this, and sorry for not getting back to you in the other issue you reported. I will soon enough 😅 

Yes, this is interesting in a few different ways. My initial idea has been this: https://github.com/zth/reason-relay/issues/43

...providing an `Fragment.useOpt` fn that takes an optional fragment ref object and optionally returns the result. It'd work the same way as passing a null reference, but it's still pretty manual of course. 

What do you think about that?

**Comment by Arnarkari93** [comment]
> Hi @Arnarkari93 , thanks for reporting this, and sorry for not getting back to you in the other issue you reported. I will soon enough 😅

Don't worry about it, I understand that it takes time.

>Yes, this is interesting in a few different ways. My initial idea has been this: #43

Allright Let's carry on this discussion in #43

**Comment by zth** [comment]
Hey again @Arnarkari93 !

Not sure if this solves your issue here per-say, but I've added a `Fragment.useOpt` in this PR: https://github.com/zth/reason-relay/pull/58

Re: moving `getFragmentRefs` up one level, I don't believe that's possible unfortunately. `getFragmentRefs` just returns _itself_ in the underlying JS, and that allows us to cast our record in Reason to a `Js.t` structure with fragment refs we can match on at the type level.

This is because of how Relay works internally - Relay needs the _object_ where the fragment was spread, so putting `getFragmentRefs` on anything but the object itself unfortunately wouldn't work.

It's unfortunate for a couple of reasons, namely because this lacks some type safety (same goes for "vanilla" Relay) since there's no way to indicate at the type level that a fragment ref is optional, without relying on Relay internals at runtime to enforce that representation. 

For now, sadly you'll need to keep track of this yourself, and use `Fragment.useOpt` and pass `None` whenever you know you haven't fetched data for that fragment yet.

Does this somewhat answer your question...? 😬

**Comment by Arnarkari93** [comment]
Yes, this makes sense. It is fine just wanted to explore the other options 🤓

**Comment by zth** [comment]
Great! I'll close this but feel free to open a new issue if you want to continue the exploration.
